### ISSUE TITLE
sneak peek?

### ISSUE THREAD

**Issue by LocationArchive** [griffpatch/griffpatch.github.io#10]
Hello griffpatch!
What are you planning on making next?
We **really** like your projects!

**Comment by LankyBox01** [comment]
*that was me, my second account

**Comment by scratchusernamemrtbts** [comment]
> *that was me, **my second account**

Are you allowed to [have more than 1 account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements)?

**Comment by LankyBox01** [comment]
> > *that was me, **my second account**
> 
> Are you allowed to [have more than 1 account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements)?

it's actually my friend's one, i am sometimes using it randomly :|

**Comment by scratchusernamemrtbts** [comment]
> > > *that was me, **my second account**
> 
> > 
> 
> > Are you allowed to [have more than 1 account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements)?
> 
> 
> 
> it's actually my friend's one, i am sometimes using it randomly :|

Oh ok
