### ISSUE TITLE
Hey Griffpatch

### ISSUE THREAD

**Issue by ZekeKokins** [griffpatch/griffpatch.github.io#30]
Hello. Griffpatch i signed up to talk to you i was wondering could you do a video about scratch 1 becuase i downloaded it today

**Comment by ZekeKokins** [comment]
here is a video of how (it is different for me because I tried downloading it twice but also if you do make a video could you like shoutout me or something thanks!)https://www.loom.com/share/82da22b1676d4af089e7b1b04b364b7e

**Comment by griffpatch** [comment]
Lol Scratch 1

**Comment by ZekeKokins** [comment]
so can you?

**Comment by ZekeKokins** [comment]
and if you do could you feature the video i sent you

**Comment by ZekeKokins** [comment]
PLEASE!!!! your are amazing at scratch

**Comment by WojtekCodesToday** [comment]
sad that a week ago, but at leasts remembers GitHub!

**Comment by ZekeKokins** [comment]
what the hell does that mean and also that was a month ago not week plus
you are not griffpatch

**Comment by griffpatch** [comment]
Sorry I don't use GitHub for chatting so these messages most of the time
pass me by...

**Comment by ZekeKokins** [comment]
okay, i will say i love your mega multplayer platformer v1.3 and then close the issue

**Comment by WojtekCodesToday** [comment]
> Sorry I don't use GitHub for chatting so these messages most of the time pass me by...

hello there griffpatch, and yes.

and i think at least of messages are from github.
