### ISSUE TITLE
Hey griffpatch I was just wondering if you could make a tutorial video on player animations for scrolling platforms (The sprites feet moving as it runs/moves) please I am trying to create a game but using the 0.1 second 

### ISSUE THREAD

**Issue by mastermakers-scratch** [griffpatch/griffpatch.github.io#6]
Hey griffpatch I was just wonderingly if it isn’t possible for you to explain through a tutorial video or even just by getting back to me, how to add player animations to scrolling platformers by that’s I mean the player moves and the legs move with it.
I tried the 0.1 second switch costume method but it’s terrible and the legs don’t automatically stop moving along when I stop, please get back to me 
mastermakers

**Comment by LankyBox01** [comment]
when green flag clicked
forever
if <key [A] pressed> then
switch costume to [left-01]
wait (0.1) secs
switch costume to [left-02]
wait (0.1) secs

do the same for every key (WASD)

**Comment by mastermakers-scratch** [comment]
I tried that it’s very basic and the player animation continues to move
after another’s key is pressed i got it to work by using the frame script
Thanks anyway
